# General configuration
host = "0.0.0.0"
port = "8000"

# User mapping allows you to map a username from one app to another. It works both ways, so you only have to define
# one mapping
user_mapping = [
    {from = "marcel", to = "marcel123"},
]

# Information for a Jellyfin instance
[jellyfin]
name = "jellyfin"
url = "https://localhost:8096"
token = "c0ffee8f39fc486392bb68f16d69b4aa"
timeout = 40
interval = 900

