name: Docker Image CI

permissions:
  packages: write

on:
  push:
    tags: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log into registry
      run: echo ${{ secrets.PACKAGE_PAT }} | docker login ghcr.io --username marcelblijleven --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/marcelblijleven/gobble:${{ github.ref_name }}
    - name: Push to registry
      run: docker push ghcr.io/marcelblijleven/gobble:${{ github.ref_name }}
