name: Bump version

on:
  push:
    branches:
      - main
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  bump_version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: "Bump version and create changelog"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - id: cz
        name: Bump version and create changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
      - run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
